version: '3.1'

networks:
  backend:
    driver: bridge

services:
  db:
    image: mariadb:10.6
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1488
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
    networks:
      - backend

volumes:
  db_data:

